### ISSUE TITLE
How do I get kerning information for a TTF file?

### ISSUE THREAD

**Issue by NathanWailes** [adobe-type-tools/kern-dump#5]
Hi,

First off, thanks for creating this and putting it on GitHub.

I'm trying to get the kerning information for a bunch of TTF fonts (including all of Google's free fonts), but when I try running kerningdump.py on an example TTF file, the script just says "The font has no GPOS table.  The fun ends here".

What's the process for getting kerning information for a TTF file?

**Comment by josh-hadley** [comment]
For .otf and .ttf files, `dumpkerning.py` will only dump kerning information that is stored in the `kern` feature of the `GPOS` table. Not all fonts contain kerning, and some that do contain kerning do not have it in the `GPOS` table. For example: many older fonts store kerning in the `kern` **table**, rather than in the `kern` feature of the `GPOS` table. `dumpkerning.py` does not support dumping kerning from those.

Which font did you try (and can you post the exact code/command used)? Maybe you just picked an unfortunate test case that doesn't have GPOS kerning.

**Comment by NathanWailes** [comment]
@josh-hadley IIRC it was "Blackadder ITC Regular".  I've got a link to a copy of the font here:
https://www.dropbox.com/s/htmd93pi66gpbj1/ITCBLKAD.TTF?dl=0

Unfortunately I don't remember the exact command I used.

**Comment by josh-hadley** [comment]
Not sure about the provenance of that font so I'm not going to touch it, but you can inspect it yourself by using `ttx -l ITCBLKAD.TTF` which will list the tables present in the font. It needs to have a `GPOS` table present (in the `tag` column) _and_ have kerning in the GPOS in order for `dumpkerning.py` to dump the kerning. I suspect you will not see a `GPOS` table when you run that command. Try other fonts that do contain GPOS kerning.
